# Generated by Django 3.2.7 on 2025-12-23 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intrution_detection', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blogs',
        ),
        migrations.DeleteModel(
            name='firewall',
        ),
        migrations.DeleteModel(
            name='guide',
        ),
        migrations.DeleteModel(
            name='hacked',
        ),
        migrations.DeleteModel(
            name='malware',
        ),
        migrations.DeleteModel(
            name='security',
        ),
        migrations.DeleteModel(
            name='webinars',
        ),
    ]
