# Generated by Django 3.2.7 on 2025-12-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intrution_detection', '0002_auto_20251224_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
