# Generated by Django 3.2.7 on 2025-12-24 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intrution_detection', '0003_auto_20251224_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='file',
        ),
    ]
