# Generated by Django 3.2.7 on 2025-12-24 10:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('intrution_detection', '0004_remove_fileupload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
